//categoryGetAll
Get http://localhost:3000/api/ProjectCategory 
//accessToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVMOtbiIsImlhdCI6MTYzNjg0OTUyMiwiZXhwIjoxNjM3MjA5NTIyfQ.QCNnxBKti5w7XocDS-lP4xWghmx7SrCzn_MgQ4gbUmU 
//done

###
//Status
Get http://localhost:3000/api/Status/getAll
//done

###
//TaskType
Get http://localhost:3000/api/TaskType/getAll


###
//priority
GET http://localhost:3000/api/Priority/getAll
//done


###
//signin
POST http://localhost:3000/api/Users/signin
Content-Type: application/json

{
  "email" : "phibang@gmail.com",
  "password": "123456"
}
//done


###
//signup
POST http://localhost:3000/api/Users/signup
Content-Type: application/json

{
  "email": "Dan@gmail.com",
  "password": "123456",
  "name": "TRanDan",
  "phoneNumber": "12456789"
}
//done

####
//edit user
PUT http://localhost:3000/api/Users/editUser
Content-Type: application/json

{
  "id": "5",
  "email": "JAV@gmail.com",
  "password": "123456",
  "name": "Bồn Lằng",
  "phoneNumber": "12456789"
}
//done

###
//getProjectDetail
Get http://localhost:3000/api/Project/getProjectDetail/id=1
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjM3Njg1ODU3LCJleHAiOjE2Mzc3NzIyNTd9.Iq_rgDBYQ92V-n8BNsSASBkLO6qKlbh8oJjtIra3V5M

###
//getAllProject
Get http://localhost:3000/api/Project/getAllProject
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjM3Njg1ODU3LCJleHAiOjE2Mzc3NzIyNTd9.Iq_rgDBYQ92V-n8BNsSASBkLO6qKlbh8oJjtIra3V5M

###
//createProject
POST  http://localhost:3000/api/Project/createProjectAuthorize
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjM3Njg1ODU3LCJleHAiOjE2Mzc3NzIyNTd9.Iq_rgDBYQ92V-n8BNsSASBkLO6qKlbh8oJjtIra3V5M
Content-Type: application/json

{
  "categoryId": 2,
  "description": "<p>Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software.</p>",
  "projectName": "Shop Bán Figure"
}

###
//delete
DELETE  http://localhost:3000/api/Project/deleteProject/projectId=7
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjM3Njg1ODU3LCJleHAiOjE2Mzc3NzIyNTd9.Iq_rgDBYQ92V-n8BNsSASBkLO6qKlbh8oJjtIra3V5M
Content-Type: application/json


###
//updatProject
PUT  http://localhost:3000/api/Project/updateProject
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "categoryId": 2,
  "description": "<p>Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software.</p>",
  "id": 1,
  "projectName": "Shop Bán Chuột"
}


###
//assignUserProject
POST   http://localhost:3000/api/Project/assignUserProject
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "projectId": 1,
  "userId": 4
}


###
//removeUserProject
POST   http://localhost:3000/api/Project/removeUserFromProject
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "projectId": 1,
  "userId": 4
}

###
//updateTask status
PUT    http://localhost:3000/api/Task/updateStatus
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 2,
  "statusId": 2
}

###
//updateTask Priority
PUT    http://localhost:3000/api/Task/updatePriority
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 2,
  "priorityId": 10
}

###
//updateTask Description
PUT    http://localhost:3000/api/Task/updateDescription
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 2,
  "description": "alo alo"
}


###
//updateTimeTracking task
PUT    http://localhost:3000/api/Task/updateTimeTracking
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 2,
  "timeTrackingSpent": 20,
  "timeTrackingRemaining": 20
}

###
//updateEstimate task
PUT    http://localhost:3000/api/Task/updateEstimate
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 2,
  "originalEstimate": "1000000"
}


###
//addUserAss task
POST     http://localhost:3000/api/Task/assignUserTask
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 1,
  "userId": 3
}


###
//removeUserTask task
POST       http://localhost:3000/api/Task/removeUserFromTask
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NzY4NzI3LCJleHAiOjE2Mzc4NTUxMjd9.YAvJtDssOZmqxW6o-xQQ9ecLByiHc_-of3d5gNmr3sA
Content-Type: application/json

{
  "taskId": 1,
  "userId": 3
}
