//categoryGetAll
Get http://localhost:5000/api/ProjectCategory 
//accessToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVMOtbiIsImlhdCI6MTYzNjg0OTUyMiwiZXhwIjoxNjM3MjA5NTIyfQ.QCNnxBKti5w7XocDS-lP4xWghmx7SrCzn_MgQ4gbUmU 
//done

###
//Status
Get http://localhost:5000/api/Status/getAll
//done

###
//TaskType
Get http://localhost:5000/api/TaskType/getAll


###
//priority
GET http://localhost:5000/api/Priority/getAll
//done


###
//signin
POST http://localhost:5000/api/Users/signin
Content-Type: application/json

{
  "email" : "tanloi@gmail.com",
  "password": "123456"
}
//done


###
//signup
POST http://localhost:5000/api/Users/signup
Content-Type: application/json

{
  "email": "Dan@gmail.com",
  "password": "123456",
  "name": "TRanDan",
  "phoneNumber": "12456789"
}
//done

####
//edit user
PUT http://localhost:5000/api/Users/editUser
Content-Type: application/json

{
  "id": "5",
  "email": "JAV@gmail.com",
  "password": "123456",
  "name": "Bồn Lằng",
  "phoneNumber": "12456789"
}
//done

###
//getProjectDetail
Get http://localhost:5000/api/Project/getProjectDetail/id=1
accesstoken:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM3NTc4NDM4LCJleHAiOjE2Mzc2NjQ4Mzh9.3yCA9-DnN7C8Zan6FzeNLcn7xfpuJ_FWCHz7LgE-rDk